/******************************************************************************
* @file           : filesystem.c
* @brief          : Source for filesystem.c file.
*                   This file contains the source code for files-related data
******************************************************************************/

#include "filesystem.h"
#include "types.h"
#include <string.h>
#include <stdio.h>

/* Global fatFS variable */
FATFS fs      = {0u};    //file system
FIL fileRead  = {0u};
FIL fileWrite = {0u};

/* Variable with common data about SD card */
FS_SDcardInfo_T sdCardInfo = {0u};


/* Init function for FS module to mount SD card and
   initialize varaibles */
void FS_Init(void)
{
    FRESULT fresult = FR_OK;

    /* Mount SD Card */
    fresult = f_mount(&fs, "", (uint8_t)FS_MOUNTNOW);

    if(FR_OK == fresult)
    {
        sdCardInfo.state = FS_INITIALIZED;
    }
    else
    {
        sdCardInfo.state = FS_UNINITIALIZED;
    }
}


/* Function called to get total size, free space and
   number of free cluster or given SD card */
FRESULT FS_GetSDcardCapacity(void)
{
    FRESULT fresult = f_getfree("", &sdCardInfo.numFreeClusters, &sdCardInfo.ptrFS);

    sdCardInfo.totalSpace = (uint32_t)(((sdCardInfo.ptrFS->n_fatent - 2u) * sdCardInfo.ptrFS->csize) / 2u);
    sdCardInfo.freeSpace = (uint32_t)((sdCardInfo.numFreeClusters * sdCardInfo.ptrFS->csize) / 2u);

    return fresult;
}


/* Main function for FS module */
void FS_Main(void)
{
    uint8_t buffer[FS_MAXBUFFSIZE] = {0u};
    uint8_t len = 0u;
    FRESULT fresult;

    /* Proceed only with properly mounted SD card */
    if(FS_INITIALIZED == sdCardInfo.state)
    {
        fresult = FS_GetSDcardCapacity();

        fresult = f_open(&fileRead, "TEST.TXT", FA_READ);
        if(FR_OK == fresult)
        {
            fresult = f_read(&fileRead, buffer, (UINT)FS_MAXBUFFSIZE, (UINT*)&len);
            fresult = f_close(&fileRead);
        }
        else
        {
            /* Set state to uninitialized. FS_Init will be trigger in the next call. */
            sdCardInfo.state = FS_UNINITIALIZED;
        }
    }
    else
    {
        FS_ReInit();
    }
}


/* Function called get one line from
   the file. */
uint8_t FS_ReadFile(uint8_t *buff, uint8_t *len)
{
    uint8_t ret = RET_NOK;
    uint8_t read = 0u;
    FRESULT fresult;

    /* Open file to read */
    fresult = f_open(&fileRead, "TEST.TXT", FA_READ);

    if(FR_OK == fresult)
    {
        /* Read string from the file */
        //f_gets(buffer, f_size(&fil), &fil);
        fresult = f_read(&fileRead, buff, (UINT)FS_MAXBUFFSIZE, (UINT*)&read);

        /* Close file */
        fresult = f_close(&fileRead);
    }

    return ret;
}


/* Function called when some fresult is not FR_OK.
   It tries to mount SD card again from higher level. */
FRESULT FS_ReInit(void)
{
    FRESULT fresult = FR_OK;

    fresult = f_close(&fileRead);
    fresult = f_mount(0u, "", (uint8_t)FS_MOUNTNOW);
    memset(&fs, 0u, sizeof(fs));
    memset(&sdCardInfo, 0u, sizeof(sdCardInfo));

    /* Autogenerated functions */
    MX_FATFS_DeInit();
    MX_FATFS_Init();

    /* Local Init */
    FS_Init();

    return fresult;
}


#if 0
  /************* The following operation is using PUTS and GETS *********************/


  /* Open file to write/ create a file if it doesn't exist */
  fresult = f_open(&fil, "file1.txt", FA_OPEN_ALWAYS | FA_READ | FA_WRITE);

  /* Writing text */
  fresult = f_puts("This data is from the First FILE\n\n", &fil);

  /* Close file */
  fresult = f_close(&fil);

  /* Open file to read */
  //fresult = f_open(&fil, "file1.txt", FA_READ);

  /* Read string from the file */
  //f_gets(buffer, fil.fsize, &fil);

  /* Close file */
  //f_close(&fil);

  /**************** The following operation is using f_write and f_read **************************/

  /* Create second file with read write access and open it */
  fresult = f_open(&fil, "file2.txt", FA_OPEN_ALWAYS | FA_READ | FA_WRITE);

  /* Writing text */
  strcpy (buffer, "This is File 2 and it says Hello from controllerstech\n");

  fresult = f_write(&fil, buffer, sizeof(buffer), &bw);

  //send_uart ("File2.txt created and data is written\n");

  /* Close file */
  f_close(&fil);

  /* Open second file to read */
  //fresult = f_open(&fil, "file2.txt", FA_READ);

  /* Read data from the file
    * Please see the function details for the arguments */
  //f_read (&fil, buffer, fil.fsize, &br);

  /* Close file */
  //f_close(&fil);

  /*********************UPDATING an existing file ***************************/

  /* Open the file with write access */
  fresult = f_open(&fil, "file2.txt", FA_OPEN_ALWAYS | FA_WRITE);

  /* Move to offset to the end of the file */
  fresult = f_lseek(&fil, f_size(&fil));

  /* write the string to the file */
  fresult = f_puts("This is updated data and it should be in the end \n", &fil);

  f_close (&fil);

  /* Open to read the file */
  //fresult = f_open (&fil, "file2.txt", FA_READ);

  /* Read string from the file */
  //f_read (&fil, buffer, fil.fsize, &br);

  /* Close file */
  //f_close(&fil);

  /*************************REMOVING FILES FROM THE DIRECTORY ****************************/

  //fresult = f_unlink("/file1.txt");

  //fresult = f_unlink("/file2.txt");

  /* Unmount SDCARD */
  fresult = f_mount(NULL, "", 1);
#endif
