/******************************************************************************
* @file           : filesystem.c
* @brief          : Source for filesystem.c file.
*                   This file contains the source code for files-related data
******************************************************************************/

#include "filesystem.h"
#include "types.h"
#include <string.h>
#include <stdio.h>

/* Static fatFS variable */
static FATFS fs      = {0u};
static FIL fileRead  = {0u};
static FIL fileWrite = {0u};

/* SD card variables*/
static FS_SDcardInfo_T sdCardInfo = {0u};
static FILINFO inFileInfo[FS_MAXINPUTFILES] = {0u};
static FILINFO outFileInfo[FS_MAXOUTPUTFILES] = {0u};


/* Init function for FS module to mount SD card and
   initialize varaibles */
void FS_Init(void)
{
    FRESULT fresult = FR_OK;

    /* Mount SD Card */
    fresult = f_mount(&fs, "", (uint8_t)FS_MOUNTNOW);

    if(FR_OK == fresult)
    {
        sdCardInfo.state = FS_INITIALIZED;
    }
    else
    {
        sdCardInfo.state = FS_UNINITIALIZED;
    }
}


/* Main function for FS module */
void FS_Main(void)
{
    uint8_t buffer[FS_MAXBUFFSIZE] = {0u};
    uint8_t len = 0u;
    FRESULT fresult;
    FILINFO fileInfo;

    /* Proceed only with properly mounted SD card */
    if(FS_INITIALIZED == sdCardInfo.state)
    {   
        fresult = FS_GetSdCardInfo();

        fresult = f_open(&fileRead, "TEST.TXT", FA_READ);
        if(FR_OK == fresult)
        {
            fresult = f_stat("TEST.TXT", &fileInfo);
            fresult = f_read(&fileRead, buffer, (UINT)FS_MAXBUFFSIZE, (UINT*)&len);
            fresult = f_close(&fileRead);
        }
        else
        {
            /* Set state to uninitialized. FS_Init will be trigger in the next call. */
            sdCardInfo.state = FS_UNINITIALIZED;
        }
    }
    else
    {
        FS_ReInit();
    }
}


/* Function called to get information
   about current SD card. */
FRESULT FS_GetSdCardInfo(void)
{
    FRESULT fresult = FR_OK;

    fresult = FS_GetSDcardCapacity();
    fresult = FS_ReadDir(FS_INPUTPATH, inFileInfo, FS_MAXINPUTFILES);
    fresult = FS_ReadDir(FS_OUTPUTPATH, outFileInfo, FS_MAXOUTPUTFILES);

    return fresult;
}


/* Function called get one line from
   the file. */
uint8_t FS_ReadFile(uint8_t *buff, uint8_t *len)
{
    uint8_t ret = RET_NOK;
    uint8_t read = 0u;
    FRESULT fresult;

    /* Open file to read */
    fresult = f_open(&fileRead, "TEST.TXT", FA_READ);

    if(FR_OK == fresult)
    {
        /* Read string from the file */
        //f_gets(buffer, f_size(&fil), &fil);
        fresult = f_read(&fileRead, buff, (UINT)FS_MAXBUFFSIZE, (UINT*)&read);

        /* Close file */
        fresult = f_close(&fileRead);
    }

    return ret;
}


/* Function called to get total size, free space and
   number of free cluster or given SD card */
FRESULT FS_GetSDcardCapacity(void)
{
    FRESULT fresult = f_getfree("", &sdCardInfo.numFreeClusters, &sdCardInfo.ptrFS);

    sdCardInfo.totalSpace = (uint32_t)(((sdCardInfo.ptrFS->n_fatent - 2u) * sdCardInfo.ptrFS->csize) / 2u);
    sdCardInfo.freeSpace = (uint32_t)((sdCardInfo.numFreeClusters * sdCardInfo.ptrFS->csize) / 2u);

    return fresult;
}


/* Function called to read directory
   on a sd card */
FRESULT FS_ReadDir(pathType path, FILINFO fileInfo[], uint8_t len)
{
    FRESULT fresult;
    DIR dir;

    fresult = f_opendir(&dir, path);

    if(FR_OK == fresult)
    {
        for(uint8_t i = 0u; i < len; i++)
        {
            fresult = f_readdir(&dir, &fileInfo[i]);
            if(0u == fileInfo[i].fsize)
            {
                break;
            }
        }
    }

    return fresult;
}


/* Function called when some fresult is not FR_OK.
   It tries to mount SD card again from higher level. */
FRESULT FS_ReInit(void)
{
    FRESULT fresult = FR_OK;

    fresult = f_close(&fileRead);
    fresult = f_mount(0u, "", (uint8_t)FS_MOUNTNOW);
    memset(&fs, 0u, sizeof(fs));
    memset(&sdCardInfo, 0u, sizeof(sdCardInfo));

    /* Autogenerated functions */
    MX_FATFS_DeInit();
    MX_FATFS_Init();

    /* Local Init */
    FS_Init();

    return fresult;
}
